language: ruby
rvm:
  - 2.2.2
  - 2.2.3
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

script: rake

notifications:
  email:
    on_success: change
    on_failure: change